# Generated by Django 4.2.1 on 2023-11-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_author_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='a_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
