# Generated by Django 4.2.1 on 2023-11-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
