# Generated by Django 4.2.1 on 2023-12-20 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_alter_comment_post_alter_reply_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
